[tool.poetry]
name = "databox"
version = "0.1.0"
description = ""
authors = ["adon <xxd.nobug@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
scrapy = "^2.12.0"
scrapyd = "^1.5.0"
pyexecjs = "^1.5.1"
scrapy-redis = "^0.9.1"
arrow = "^1.3.0"
httpx = "^0.28.1"
pillow = "^11.1.0"
pyzbar = "^0.1.9"
aiohttp = "^3.11.11"
playwright-stealth = "^1.0.6"
pydantic = "^2.10.5"
sqlalchemy = "^2.0.37"
peewee = "^3.17.8"
pymongo = "^4.10.1"
selenium = "^4.27.1"
pycryptodome = "^3.21.0"
qrcode = "^8.0"
mitmproxy = "^11.1.0"
opencv-python = "^4.10.0.84"
pytesseract = "^0.3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
