[project]
name = "databox"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "scrapy (>=2.12.0,<3.0.0)",
    "scrapyd (>=1.5.0,<2.0.0)",
    "pyexecjs (>=1.5.1,<2.0.0)",
    "scrapy-redis (>=0.9.1,<0.10.0)",
    "arrow (>=1.3.0,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pillow (>=11.1.0,<12.0.0)",
    "pyzbar (>=0.1.9,<0.2.0)",
    "aiohttp (>=3.11.11,<4.0.0)",
    "playwright-stealth (>=1.0.6,<2.0.0)",
    "pydantic (>=2.10.5,<3.0.0)",
    "sqlalchemy (>=2.0.37,<3.0.0)",
    "peewee (>=3.17.8,<4.0.0)",
    "pymongo (>=4.10.1,<5.0.0)",
    "selenium (>=4.27.1,<5.0.0)",
    "pycryptodome (>=3.21.0,<4.0.0)",
    "qrcode (>=8.0,<9.0)",
    "mitmproxy (>=11.1.0,<12.0.0)",
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    "pytesseract (>=0.3.13,<0.4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"