name: Databox Project Deploy

on:
  workflow_dispatch:

jobs:
  run-scrapy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scrapy crawlers
        run: |
          python databox/github/submit-mcp.py